apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
patchesStrategicMerge:
- config.yml
- ingress.yml
patches:
- path: ingress-patch.yml
  target:
    group: networking.k8s.io
    version: v1
    kind: Ingress
    name: argocd-server
namespace: argocd
